close all;
clear all;
clc;

load('DFCR.mat');
DFCR_2 = DEAD;
load('Dijkstra.mat');
Dijkstra_2 = DEAD;
load ('Greedy.mat');
Greedy_2 = DEAD;
load('DFCR_scen1.mat');
DFCR_1 = DEAD;
load('Dijkstra_scen1.mat');
Dijkstra_1 = DEAD;
load ('Greedy_scen1.mat');
Greedy_1 = DEAD;

y1 = [find(DFCR_1,1) find(Dijkstra_1,1) find(Greedy_1,1); find(DFCR_2,1) find(Dijkstra_2,1) find(Greedy_2,1)];
figure(1);
hb = bar(y1);
set(gca,'xticklabel',{'scenario1','scenario2'},'FontWeight','bold');
ylabel('Rounds','FontWeight','bold');
legend('DFCR','Dijkstra','Greedy');
figure(2);
a1=find(DFCR_1==50);
a2=find(Dijkstra_1==50);
a3=find(Greedy_1==50); 
a4=find(DFCR_2==50); 
a5=find(Dijkstra_2==50); 
a6=find(Greedy_2==50);
y2 = [a1(1) a2(1) a3(1);a4(1) a5(1) a6(1)];
hb = bar(y2);
set(gca,'xticklabel',{'scenario1','scenario2'},'FontWeight','bold');
ylabel('Rounds','FontWeight','bold');
legend('DFCR','Dijkstra','Greedy');
figure(3);
a1=find(DFCR_1==99);
a2=find(Dijkstra_1==99);
a3=find(Greedy_1==99); 
a4=find(DFCR_2==99); 
a5=find(Dijkstra_2==99); 
a6=find(Greedy_2==99);
y2 = [a1(1) a2(1) a3(1);a4(1) a5(1) a6(1)];
hb = bar(y2);
set(gca,'xticklabel',{'scenario1','scenario2'},'FontWeight','bold');
ylabel('Rounds','FontWeight','bold');
legend('DFCR','Dijkstra','Greedy');
